# Generated by Django 4.1.5 on 2023-09-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('kz', 'KZ'), ('ru', 'RU')], default='ru', max_length=10),
        ),
    ]
