# Generated by Django 4.1.5 on 2023-10-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='poster',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='products_posters/'),
        ),
    ]
