# Generated by Django 4.1.5 on 2023-12-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_discount_percentage'),
        ('product', '0013_product_boutique_alter_product_market'),
    ]

    operations = [
    ]
