# Generated by Django 4.1.5 on 2023-12-18 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplier_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0014_merge_20231205_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='card_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'В обработке'), ('accepted', 'Активный'), ('canceled', 'Отклоненный')], default='new', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
