# Generated by Django 4.1.5 on 2023-12-19 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_supplier_bad_remarks_count_and_more'),
        ('product', '0016_alter_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='supplier.supplier'),
        ),
    ]
