# Generated by Django 4.1.5 on 2023-12-05 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'В обработке'), ('purchased', 'Куплен'), ('not_available', 'Нет в наличий'), ('will_be_tomorrow', 'Будет завтра'), ('replaced', 'Заменён'), ('is_being_considered', 'Рассматривается')], default='new', max_length=50)),
                ('price_per_count', models.PositiveIntegerField(default=0)),
                ('replaced_by_product_image', models.ImageField(blank=True, null=True, upload_to='replaced_by_product_image/')),
                ('is_sorted', models.BooleanField(blank=True, default=False, null=True)),
                ('last_modified', models.DateTimeField(default=project.utils.datetime_now)),
                ('is_purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.buyer')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='order.orderitem')),
            ],
        ),
    ]
