# Generated by Django 4.1.5 on 2023-11-23 19:04

from django.db import migrations, models
import project.utils


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_purchase_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='last_modified',
            field=models.DateTimeField(default=project.utils.datetime_now),
        ),
    ]
