# Generated by Django 4.1.5 on 2023-11-27 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_purchase_is_purchased_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='is_purchased_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.buyer'),
        ),
    ]
