# Generated by Django 4.1.5 on 2023-11-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_alter_purchase_is_purchased_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='replaced_by_product',
        ),
        migrations.AddField(
            model_name='purchase',
            name='replaced_by_product_image',
            field=models.ImageField(blank=True, null=True, upload_to='replaced_by_product_image/'),
        ),
    ]
