# Generated by Django 4.1.5 on 2023-11-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_remove_purchase_replaced_by_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchased_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
