# Generated by Django 4.1.5 on 2023-12-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_remove_purchase_purchased_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('new', 'В обработке'), ('purchased', 'Куплен'), ('not_available', 'Нет в наличий'), ('will_be_tomorrow', 'Будет завтра'), ('replaced', 'Заменён'), ('is_being_considered', 'Рассматривается')], default='new', max_length=50),
        ),
    ]
