# Generated by Django 4.1.5 on 2023-12-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_alter_purchase_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='sorted_report',
        ),
    ]
