# Generated by Django 4.1.5 on 2023-12-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_alter_buyer_account_alter_purchase_is_purchased_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='check_defects',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='check_defects_checkbox',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='with_gift',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='with_gift_checkbox',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
