# Generated by Django 4.1.5 on 2023-03-25 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=False)),
                ('poster', models.ImageField(max_length=500, upload_to='category_posters/')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryFiltration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtration', to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryFiltrationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('category_filtration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='category.categoryfiltration')),
            ],
        ),
    ]
