# Generated by Django 4.1.5 on 2023-11-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_time', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changetime',
            name='dt',
            field=models.DateField(unique=True),
        ),
    ]
