# Generated by Django 4.1.5 on 2023-12-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('ruble', 'рубль'), ('tenge', 'тенге')], default='ruble', max_length=255),
        ),
    ]
