# Generated by Django 4.1.5 on 2023-12-18 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supplier', to=settings.AUTH_USER_MODEL),
        ),
    ]
