# Generated by Django 4.1.5 on 2023-12-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplier_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='boutique',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='market',
            field=models.CharField(choices=[('sadovod', 'Садовод'), ('yuzhnye_vorota', 'Южные ворота')], default='sadovod', max_length=255),
        ),
    ]
