# Generated by Django 4.1.5 on 2023-12-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplier_boutique_supplier_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='bad_remarks_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='good_remarks_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
