# Generated by Django 4.1.5 on 2023-12-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_supplier_bad_remarks_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='bad_remarks_count',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='good_remarks_count',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
