# Generated by Django 4.1.5 on 2023-08-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='device1',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='device2',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
