# Generated by Django 4.1.5 on 2023-08-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_client_device1_client_device2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='device1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='device2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
