# Generated by Django 4.1.5 on 2023-09-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_client_device1_alter_client_device2'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ignore_device_verification',
            field=models.BooleanField(default=False),
        ),
    ]
