# Generated by Django 4.1.5 on 2023-11-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='device3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
