# Generated by Django 4.1.5 on 2023-12-05 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='super_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
