# Generated by Django 4.1.5 on 2023-12-27 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0010_alter_client_account_alter_superadmin_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_cards', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
