# Generated by Django 4.1.5 on 2023-12-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_mycard'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycard',
            name='last_status',
            field=models.CharField(default='just_created', max_length=255),
        ),
    ]
