# Generated by Django 4.1.5 on 2024-01-03 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_price'),
        ('user', '0012_mycard_last_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycard',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_cards', to='product.product'),
        ),
    ]
