# Generated by Django 4.1.5 on 2023-11-07 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0010_alter_product_poster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveries_qr_code', models.FileField(upload_to='deliveries_qr_code/')),
                ('selection_sheet_file', models.FileField(upload_to='selection_sheet_files/')),
                ('is_express', models.BooleanField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('paid_check_file', models.FileField(upload_to='paid_check_files/')),
                ('ruble_rate', models.FloatField()),
                ('total_products_count', models.PositiveIntegerField()),
                ('service_price_per_count', models.PositiveIntegerField()),
                ('express_price', models.PositiveIntegerField()),
                ('total_service_price', models.PositiveIntegerField()),
                ('total_products_price', models.PositiveIntegerField()),
                ('total_sum_in_tenge', models.FloatField()),
                ('total_sum_in_ruble', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('qr_code', models.FileField(upload_to='products_qr_code/')),
                ('product_price', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
