# Generated by Django 4.1.5 on 2023-11-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_one_file_products_qr_codes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='express_price',
            new_name='express_price_per_count',
        ),
    ]
