# Generated by Django 4.1.5 on 2023-11-11 20:02

from django.db import migrations, models
import project.utils


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_express_price_order_express_price_per_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateField(default=project.utils.datetime_now, editable=False),
        ),
    ]
