# Generated by Django 4.1.5 on 2023-11-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_for_specific_product',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='specific_product',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
