# Generated by Django 4.1.5 on 2023-11-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_price_for_specific_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новые'), ('accepted', 'Принятые')], default='new', max_length=100),
        ),
    ]
