# Generated by Django 4.1.5 on 2023-11-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='one_file_products_qr_codes',
        ),
    ]
