# Generated by Django 4.1.5 on 2023-11-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_one_file_products_qr_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, default='new', max_length=255),
        ),
    ]
