# Generated by Django 4.1.5 on 2023-11-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_orderitem_status_orderitempurchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItemPurchase',
        ),
    ]
