# Generated by Django 4.1.5 on 2023-11-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_delete_orderitempurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_sorting_by',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
