# Generated by Django 4.1.5 on 2023-11-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_sorted_report',
            field=models.ImageField(blank=True, null=True, upload_to='order_is_sorted_reports/'),
        ),
    ]
