# Generated by Django 4.1.5 on 2023-11-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_delivered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sorted_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
