# Generated by Django 4.1.5 on 2023-11-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_order_accepted_dt_order_delivered_dt_order_sorted_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'В обработке'), ('accepted', 'Принят'), ('is_sorting', 'Сортируется'), ('sorted', 'Сортирован'), ('delivered', 'Отправлен')], default='new', max_length=100),
        ),
    ]
