# Generated by Django 4.1.5 on 2023-12-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_remove_order_is_sorted_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sorted_report',
            field=models.ImageField(blank=True, null=True, upload_to='order_is_sorted_reports/'),
        ),
    ]
