# Generated by Django 4.1.5 on 2023-12-05 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_manager_account'),
        ('order', '0021_alter_order_manager_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.manager'),
        ),
    ]
