# Generated by Django 4.1.5 on 2023-12-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_order_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
