# Generated by Django 4.1.5 on 2023-12-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_order_is_same_with_last_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'В обработке'), ('accepted', 'Принят'), ('is_sorting', 'Сортируется'), ('sorted', 'Сортирован'), ('delivered', 'Отправлен'), ('canceled', 'Отмененые')], default='new', max_length=100),
        ),
    ]
