# Generated by Django 4.1.5 on 2023-12-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_orderreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='check_defects',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='with_gift',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
